services:
  - type: web
    name: vehicle-stats
    env: python
    pythonVersion: 3.12.4
    aptPackages:
      - unixodbc-dev
    buildCommand: pip install -r /opt/render/project/src/requirements.txt
    startCommand: /opt/render/project/src/.venv/bin/gunicorn app:app
    plan: free
    envVars:
      - key: PORT
        value: 10000
