services:
  - type: web
    name: vehicle-stats
    env: python
    pythonVersion: 3.12.4
    aptPackages:
      - unixodbc-dev
    buildCommand: /opt/render/project/src/render-build.sh
    startCommand: /opt/render/project/src/render-start.sh
    plan: free
    envVars:
      - key: PORT
        value: 10000
