services:
  - type: web
    name: Silverlake.IAA
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m gunicorn app:app
    plan: free
    envVars:
      - key: PORT
        value: 10000
