services:
  - type: web
    name: part-sales-opportunity
    env: python
    buildCommand: ./render-build.sh
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: PORT
        value: 10000

