Ã±services:
  - type: web
    name: part-sales-opportunity
    env: python
    buildCommand: pip install -r /opt/render/project/src/requirements.txt
    startCommand: /opt/render/project/src/.venv/bin/gunicorn app:app
    plan: free
    envVars:
      - key: PORT
        value: 10000
  - type: web
    name: vehicle-stats
    env: python
    rootDir: vehicle_stats_app
    buildCommand: pip install -r /opt/render/project/src/requirements.txt
    startCommand: /opt/render/project/src/.venv/bin/gunicorn app:app
    plan: free
    envVars:
      - key: PORT
        value: 10000
