services:
  - type: web
    name: vehicle_stats_app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: USERS_FILE_PATH
        value: /var/data/users.json
