services:
  - type: web
    name: part-sales-opportunity
    env: python
    buildCommand: /opt/render/project/src/render-build.sh
    startCommand: /opt/render/project/src/render-start.sh
    plan: free
    envVars:
      - key: PORT
        value: 10000
  - type: web
    name: vehicle-stats
    env: python
    rootDir: vehicle_stats_app
    buildCommand: /opt/render/project/src/render-build.sh
    startCommand: /opt/render/project/src/render-start.sh
    plan: free
    envVars:
      - key: PORT
        value: 10000
